### ISSUE TITLE
 Failure sending mail -  Laminas\Mail\Transport\Smtp

### ISSUE THREAD

**Issue by jmpicazo** [ubermanu/magento2-email#2]
When I try to send an email this error pops up, I have tried several target email accounts to send the emails, but it still gives these errors.

**In Transport.php line 141:**
                                                                                                                            
`Laminas\Mail\Transport\Smtp transport expects either a Sender or at least one From address in the Message; none provided  `
                                                                                                                            

**In Smtp.php line 307:**
                                                                                                                            
`Laminas\Mail\Transport\Smtp transport expects either a Sender or at least one From address in the Message; none provided`

**Comment by ubermanu** [comment]
hey,

can you give me details about:
- the command(s) you were running
- your Magento 2 version

I just tested it on 2.3 and it seems to run fine (on a DDEV environment though)

**Comment by jmpicazo** [comment]
Hi,

- Magento Version Magento CLI 2.4.2
- php bin/magento email:send -t customer_create_account_email_template -s 0 -i variables.yml picazoquijarro@gmail.com

variables.yml
```
customer:
  id: 1
  name: John Doe
  email: juan.picazo@farmaciasvivo.com
```

Thanks  !

**Comment by ubermanu** [comment]
I've added a sender email (from the store config), it should fix your problem see https://github.com/ubermanu/magento2-email/commit/6d22396bc6e2294c171da4c4da78aee42f8be06a

you can try it using the master branch or update to the version 1.3.1 (should be published soon on packagist 👍)

EDIT:

also, i noticed that the template will throw a soft error if the `rp_token` value is missing in the variables
it should be:

```yaml
customer:
  id: 1
  name: John Doe
  email: juan.picazo@farmaciasvivo.com
  rp_token:
```

**Comment by jmpicazo** [comment]
First, thank you very much for the fast update, second, I have done tests and it works perfectly. I am working on the variables.yml file to improve the information sent. Thanks

**Comment by ubermanu** [comment]
cheers!
